# Generated by Django 4.2.3 on 2023-07-25 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excercize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(max_length=50, verbose_name='muscle')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('sets', models.DecimalField(decimal_places=0, max_digits=2)),
                ('reps', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Strech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(max_length=50, verbose_name='muscle')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('sets', models.DecimalField(decimal_places=0, max_digits=2)),
                ('reps', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('Strech', models.ManyToManyField(to='program.strech')),
                ('excercize', models.ManyToManyField(to='program.excercize')),
            ],
        ),
    ]
