# Generated by Django 4.2.3 on 2023-07-25 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wight',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='pvz 1.68', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='info',
            field=models.TextField(blank=True, help_text='svarbi informacija', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
