# Generated by Django 4.2.3 on 2023-07-26 07:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0004_remove_program_strech_remove_program_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['date_created', 'user']},
        ),
        migrations.AlterModelOptions(
            name='programday',
            options={'ordering': ['user', 'day_number']},
        ),
        migrations.RemoveField(
            model_name='programday',
            name='date_created',
        ),
        migrations.AddField(
            model_name='program',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='programday',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='program_days', to='program.programday'),
        ),
    ]
