# Generated by Django 4.2.3 on 2023-07-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_alter_programday_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programday',
            options={'ordering': ['day_number']},
        ),
        migrations.RemoveField(
            model_name='programday',
            name='user',
        ),
    ]
