# Generated by Django 4.2.3 on 2023-07-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_programday_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programday',
            name='excercize',
            field=models.ManyToManyField(blank=True, to='program.excercize'),
        ),
        migrations.AlterField(
            model_name='programday',
            name='strech',
            field=models.ManyToManyField(blank=True, to='program.strech'),
        ),
    ]
