# Generated by Django 4.2.3 on 2023-07-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_alter_programday_excercize_alter_programday_strech'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(max_length=50, verbose_name='muscle')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercize_pics')),
                ('sets', models.DecimalField(decimal_places=0, max_digits=2)),
                ('reps', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='programday',
            name='excercize',
        ),
        migrations.DeleteModel(
            name='Excercize',
        ),
        migrations.AddField(
            model_name='programday',
            name='exercize',
            field=models.ManyToManyField(blank=True, to='program.exercize'),
        ),
    ]
