# Generated by Django 4.2.3 on 2023-07-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_exercize_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercize',
            new_name='Exercise',
        ),
        migrations.RenameField(
            model_name='programday',
            old_name='exercize',
            new_name='exercise',
        ),
    ]
